# --- !Ups

create table "Publisher" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "phone_number" VARCHAR2(20) not null UNIQUE
);

create table "Subscriber" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "phone_number" VARCHAR2(20) not null UNIQUE,
  "language" varchar2(3),
  "state" varchar2(20) not null,

);

# --- !Downs