from ae519af3ac30


CMD [ \
  "/bin/bash", \
  "-c", \
  "echo ./target/universal/stage/bin/smsalertsystemv2 \
     -Dplay.evolutions.db.default.autoApply=true \
     -Dslick.dbs.default.db.user=root \
     -Dslick.dbs.default.db.password=$MYSQL_ROOT_PASSWORD \
     -Dauth0.domain=$AUTH0_DOMAIN \
     -Dauth0.clientId=$AUTH0_CLIENT_ID \
     -Dauth0.clientSecret=$AUTH0_CLIENT_SECRET \
     -Dauth0.callbackURL=$AUTH0_CALLBACK_URL \
     -Dauth0.audience=$AUTH0_AUDIENCE \
     -Dtwilio.username=$TWILIO_USERNAME \
     -Dtwilio.password=$TWILIO_PASSWORD \
     -Dtwilio.phone=$TWILIO_PHONE \
     -Dplay.http.secret.key=$PLAY_SECRET_KEY" \
]
