version: "3.6"
services:
  sms:
    build:
      context: .
    command: [
      "./target/universal/stage/bin/smsalertsystemv2",
        "-Dplay.evolutions.db.default.autoApply=true",
        "-Dplay.http.secret.key=${PLAY_SECRET}",
        "-Dslick.dbs.default.db.url=jdbc:mysql://mysql:3306/${MYSQL_DB}",
        "-Dslick.dbs.default.db.user=root",
        "-Dslick.dbs.default.db.password=${MYSQL_ROOT_PASSWORD}",
        "-Daws.region=${AWS_REGION}",
        "-Dauth0.domain=${AUTH0_DOMAIN}",
        "-Dauth0.clientId=${AUTH0_CLIENT_ID}",
        "-Dauth0.clientSecret=${AUTH0_CLIENT_SECRET}",
        "-Dauth0.callbackURL=${AUTH0_CALLBACK_URL}",
        "-Dauth0.audience=${AUTH0_AUDIENCE}",
        "-Dtwilio.username=${TWILIO_USERNAME}",
        "-Dtwilio.password=${TWILIO_PASSWORD}",
        "-Dtwilio.phone=${TWILIO_PHONE}"
    ]
    depends_on:
      - db
    links:
      - db:mysql
    networks:
      - service_network
    ports:
      - "9000:9000"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    networks:
      service_network:
        aliases:
          - mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  service_network:
